/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.asdfa.developingspace.taskstack;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;

/**
 *
 * @author austin
 */
public class TaskItemPanel extends javax.swing.JPanel {

	private final TaskStack taskStack;

	/**
	 * Creates new form TaskItemPanel
	 */
	public TaskItemPanel(String taskString, TaskStack taskStack) {
		initComponents();
		txtTaskDiscrip.setText(taskString);
		this.taskStack = taskStack;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTaskDiscrip = new javax.swing.JTextArea();
        btnPop = new javax.swing.JButton();

        jTextField1.setText("jTextField1");
        jTextField1.setName("jTextField1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtTaskDiscrip.setColumns(20);
        txtTaskDiscrip.setLineWrap(true);
        txtTaskDiscrip.setRows(1);
        txtTaskDiscrip.setName("txtTaskDiscrip"); // NOI18N
        jScrollPane1.setViewportView(txtTaskDiscrip);

        btnPop.setText("Pop");
        btnPop.setName("btnPop"); // NOI18N
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(btnPop)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed
		Container parent = getParent();
		if (parent != null){
			parent.remove(this);
			parent.revalidate();
			parent.repaint();
			taskStack.tasks.remove(this);
		}
    }//GEN-LAST:event_btnPopActionPerformed


	public void setTaskText(String text){
		txtTaskDiscrip.setText(text);
	}
	public String getTaskText(){
		return txtTaskDiscrip.getText();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPop;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtTaskDiscrip;
    // End of variables declaration//GEN-END:variables

	@Override
	public Dimension getPreferredSize() {
		Dimension result = super.getPreferredSize();
		result.height = txtTaskDiscrip.getPreferredSize().height + 10;
		return result;
	}


}
