/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.asdfa.developingspace.taskstack;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.StringJoiner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author austin
 */
public class TaskStack extends javax.swing.JFrame {

	final List<TaskItemPanel> tasks = new ArrayList<>(10);
	static final char ENTRY_SEPARATOR = '\u001e';
	/**
	 * Creates new form TaskStack
	 */
	public TaskStack() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlTasks = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNewTask = new javax.swing.JTextArea();
        btnPush = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        pnlTasks.setName("pnlTasks"); // NOI18N
        pnlTasks.setLayout(new javax.swing.BoxLayout(pnlTasks, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlTasks);

        btnSave.setText("Save");
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        txtNewTask.setColumns(20);
        txtNewTask.setLineWrap(true);
        txtNewTask.setRows(5);
        txtNewTask.setName("txtNewTask"); // NOI18N
        txtNewTask.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewTaskKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtNewTask);

        btnPush.setText("Push");
        btnPush.setName("btnPush"); // NOI18N
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.setName("btnLoad"); // NOI18N
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPush))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoad)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnLoad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPush))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
		pushTask();
    }//GEN-LAST:event_btnPushActionPerformed

	private void pushTask() {
		String taskText = txtNewTask.getText();
		if (null == taskText || "".equals(taskText.trim())) {
			txtNewTask.setText("");
			return;
		}
		taskText = taskText.trim();
		TaskItemPanel panel = new TaskItemPanel(taskText, this);
		pnlTasks.add(panel, 0);
		tasks.add(panel);
		txtNewTask.setText("");
		pnlTasks.revalidate();
		pnlTasks.repaint();
	}

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        JFileChooser chooser = new JFileChooser();
		FileFilter filter = new FileNameExtensionFilter("Task Stack", "dat");
		chooser.addChoosableFileFilter(filter);
		chooser.setFileFilter(filter);
		if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION){
			return;
		}
		String content;
		List<String> lines;
		try{
			lines = Files.readAllLines(chooser.getSelectedFile().
					toPath());
		}
		catch (IOException ioe){
			JOptionPane.showMessageDialog(this, ioe, "Load Error",
					JOptionPane.ERROR_MESSAGE);
			return;
		}
		StringJoiner joiner = new StringJoiner("\n");
		lines.forEach(joiner::add);
		content = joiner.toString();
		pnlTasks.removeAll();
		tasks.clear();
		String[] tasksArray = content.split(ENTRY_SEPARATOR + "");
		for (String task : tasksArray) {
			if (null == task || "".equals(task.trim())){
				continue;
			}
			TaskItemPanel tip = new TaskItemPanel(task, this);
			pnlTasks.add(tip, 0);
			tasks.add(tip);
		}
		pnlTasks.revalidate();
		pnlTasks.repaint();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser chooser = new JFileChooser();
		FileFilter filter = new FileNameExtensionFilter("Task Stack", "dat");
		chooser.addChoosableFileFilter(filter);
		chooser.setFileFilter(filter);
		if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION){
			return;
		}
		List<String> stringTasks = new ArrayList<>(tasks.size());
		for (TaskItemPanel task : tasks) {
			stringTasks.add(task.getTaskText());
		}
		try(OutputStreamWriter writer = new OutputStreamWriter(
				new FileOutputStream(chooser.getSelectedFile(), false))){
			boolean first = true;
			for (String stringTask : stringTasks) {
				if (first){
					first = false;
				}
				else{
					writer.append(ENTRY_SEPARATOR);
				}
				writer.append(stringTask);
			}
			writer.flush();
		}
		catch (IOException ioe){
			JOptionPane.showMessageDialog(this, ioe, "Save Error",
					JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNewTaskKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewTaskKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER &&
				evt.getModifiers() == Toolkit.getDefaultToolkit().
						getMenuShortcutKeyMask()){
			pushTask();
		}
    }//GEN-LAST:event_txtNewTaskKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TaskStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TaskStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TaskStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TaskStack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new TaskStack().setVisible(true);
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlTasks;
    private javax.swing.JTextArea txtNewTask;
    // End of variables declaration//GEN-END:variables
}
